--DROP TABLE IF EXISTS Category;
--
--CREATE TABLE Category
--(
--    id int PRIMARY KEY IDENTITY,
--    name        VARCHAR(50)    NOT NULL,
--    description VARCHAR(255)
--);
--
--DROP TABLE IF EXISTS Hardware;
--
--CREATE TABLE Hardware
--(
--    id int PRIMARY KEY IDENTITY,
--    name        VARCHAR(50)    NOT NULL,
--    description VARCHAR(255),
--    price       DECIMAL(10, 2) NOT NULL,
--    categoryId  INT,
--    FOREIGN KEY (categoryId) REFERENCES Category(id)
--);
